### ISSUE TITLE
(More a request)   Getting the output working.

### ISSUE THREAD

**Issue by Just-another-pleb** [DaveMDS/node-red-contrib-tasmota#1] opened 2019-12-10 22:36 UTC
Thanks very much for the node.   It is great.

Alas I am not getting it all on how to use it.

"Out of the box" the node shows an "online" signal - which is good.
But when I set it for 3 switches and the like, the node condition changes to "offline", and I don't get why.

I am also having a lot of trouble getting the output/s working.

I have 3 `debug` nodes on the 3 outputs, but turning the outputs on/off nothing is seen in the debug nodes.   (They are set to display all)

**Comment by DaveMDS** [comment] 2019-12-11 18:17
Hi, 
does it work when configured as "1 Channel (or all merged)" ? you should still get messages for all the 3 switches on the single output.

Can I ask what device do you have with 3 switches? I only tested with a 2CH Sonoff

Do you know the MQTT topic/cmnd your device support (tough it should be the same for all 
tasmota flashed device)

Please also attach some screenshots of the situation

**Comment by Just-another-pleb** [comment] 2019-12-15 20:33
Ok, here are a couple of flows:

(Pictures)

![This works](https://user-images.githubusercontent.com/39888280/70868481-6880fb80-1fd5-11ea-8efb-731b473e5cf7.png)

This is the flow with your node.

When I toggle the outputs, I am not getting anything in the `debug` nodes.

![Screenshot from 2019-12-16 07-22-42](https://user-images.githubusercontent.com/39888280/70868489-8189ac80-1fd5-11ea-8524-d478306edba7.png)

This is the code:

[SONOFF.txt](https://github.com/DaveMDS/node-red-contrib-tasmota/files/3965414/SONOFF.txt)

The board is a Bauhn 3 point board.

This is the working code:

[Working_Sonoff.txt](https://github.com/DaveMDS/node-red-contrib-tasmota/files/3965417/Working_Sonoff.txt)

Obviously I am missing something simple.  Sorry.   That's where I am at.

Thanks.

**Comment by DaveMDS** [comment] 2019-12-16 22:01
This is so strange... your configuration seems correct to me, 
you are able to control you device using the tasmota node right?

seems your device is not sending the `stat/<device>/POWER+` message I'm listening to.

From you working flow I see you can get the state subscribing to `stat/<device>/RESULT/#`,
can you try listening to `stat/<device>/POWER+` instead? to see if your device is sending that reply.
Or just use the mqtt-catch-all node so see all the traffic.

My tasmota always send 2 msgs when the state change:
 * stat/<device>/POWER1 On
 * stat/<device>/RESULT {"POWER1": "ON"}
is the same for you?

Thanks for testing :)

**Comment by Just-another-pleb** [comment] 2019-12-17 05:11
If all fields are blank, it (the node) shows as ONLINE when powered up.   Nice.

Adding:  `stat/BAUHN-1/RESULT/#` to the `advanced/stat` field, it becomes OFFLINE.

<s>
Clicking the `inject` nodes the respecting outputs toggle (turn on/off) so that part works.
Alas now the ONLINE part doesn't work.
To get it back to showing ONLINE I have to power down the board and power it back up with the field blank.
</s>

Sorry.   I have to power cycle the board if I change the field.

Still doesn't get an output.

I think the `+` is a problem with the `MQTT` node.

Making the `MQTT` listen to 
`stat/BAUHN-1/#`

I get:
```
{"topic":"stat/BAUHN-1/RESULT","payload":"{\"POWER1\":\"ON\"}","qos":0,"retain":false,"_msgid":"96eb3d3a.240d7"}
```

So that looks better, but your node isn't playing the game.

So here is the node as now configured:
(only because I am so stupid, could you put proper topic name.   I fell for cutting/pasting what you wrote and wondered why it didn't work.  See above.)

```
[{"id":"47a3b1ab.b25ff8","type":"Tasmota Switch","z":"9245b569.9f881","broker":"8a2e80be.f7c928","device":"BAUHN-1","name":"Bauhn 1","topicMode":"0","cmndPrefix":"","statPrefix":"stat/BAUHN-1/RESULT/#","telePrefix":"","outputs":3,"onValue":"","offValue":"","toggleValue":"","x":510,"y":1390,"wires":[["eec8a5ad.4a5dd"],["20c62106.1e6fde"],["33f8c8b1.e93cd8"]]},{"id":"8a2e80be.f7c928","type":"mqtt-broker","z":"","name":"MQTT host","broker":"192.168.0.99","port":"1883","clientid":"","usetls":false,"compatmode":true,"keepalive":"60","cleansession":true,"birthTopic":"ARDUINO_STATUS","birthQos":"2","birthPayload":"connected","willTopic":"ARDUINO_STATUS","willQos":"0","willPayload":"disconnected"}]
```

On the last part:  Yes mine sends two messages too - it seems.

1:  `{"topic":"stat/BAUHN-1/RESULT","payload":"{\"POWER1\":\"ON\"}","qos":0,"retain":false,"_msgid":"96eb3d3a.240d7"}`
2: `{"topic":"stat/BAUHN-1/POWER1","payload":"ON","qos":0,"retain":false,"_msgid":"313b5932.d72526"}`

Does that help?

**Comment by DaveMDS** [comment] 2019-12-17 20:15
So you are receiving two messages like me, and they are formatted as expected, it should work...
The node internally subscribe to `stat/BAUHN-1/POWER+` and therefore it should send a true/false to the output when `stat/BAUHN-1/POWER1` is fired by your device.

In your last posted config I see you changed the Advanced->stat option, that one is wrong, you must just leave all advanced options empty, as per default.

The only needed config for the Tasmota node to work is the Device field, that you already correctly set. All other options can be left blank.

This simple example works for me, try to import it. Just change the broker and the device (mine is called sonoff1) and it should work (leave all advanced confs blank)
```
[{"id":"b271d1f7.454fc8","type":"Tasmota Switch","z":"484d0292.f716d4","broker":"de75f515.413bc8","device":"sonoff1","name":"Bauhn 1","topicMode":"0","cmndPrefix":"","statPrefix":"","telePrefix":"","outputs":3,"onValue":"","offValue":"","toggleValue":"","x":420,"y":280,"wires":[["32c2f909.58d766"],[],[]]},{"id":"de75f515.413bc8","type":"mqtt-broker","z":"","name":"MQTT Broker","broker":"192.168.1.170","port":"1883","clientid":"NodeRed","usetls":false,"compatmode":false,"keepalive":"60","cleansession":true,"birthTopic":"","birthQos":"0","birthPayload":"","closeTopic":"","closeQos":"0","closePayload":"","willTopic":"","willQos":"0","willPayload":""}]
```
![immagine](https://user-images.githubusercontent.com/52688/71030584-08dc3a80-2112-11ea-9571-23307cfca21a.png)

**Comment by Just-another-pleb** [comment] 2019-12-18 02:35
Sorry, but I see "problems" with what you just said.

>  The node internally subscribe to stat/BAUHN-1/POWER+

But in your screen shot it is Bauhn 1
(no `-` between the name and the number)
and the device is sonoff1

So where does the
BAUHN-1 come into play?

I'm trying what you said.

I think the "problem" is also what I called the power board too.
But I am still no closer to understanding what is what.

What is the `device` field and what is the `name` field?
I'm guessing the `name` is what NR shows it as in the flow and the `device` is the name of the device.

Dunno.

**Comment by Just-another-pleb** [comment] 2019-12-18 02:55
HURRAY!

This config works!

```
[{"id":"47a3b1ab.b25ff8","type":"Tasmota Switch","z":"9245b569.9f881","broker":"8a2e80be.f7c928","device":"BAUHN-1","name":"Bauhn 1","topicMode":"0","cmndPrefix":"","statPrefix":"","telePrefix":"","outputs":3,"onValue":"","offValue":"","toggleValue":"","x":520,"y":1560,"wires":[["eec8a5ad.4a5dd"],["20c62106.1e6fde"],["33f8c8b1.e93cd8"]],"info":"Old device name\nBAUHN-1\n"},{"id":"8a2e80be.f7c928","type":"mqtt-broker","z":"","name":"MQTT host","broker":"192.168.0.99","port":"1883","clientid":"","usetls":false,"compatmode":true,"keepalive":"60","cleansession":true,"birthTopic":"ARDUINO_STATUS","birthQos":"2","birthPayload":"connected","willTopic":"ARDUINO_STATUS","willQos":"0","willPayload":"disconnected"}]
```

Maybe what was stumping me was in the advanced settings.

I had the `stat` line with text in it which was *wrong*/not helping.

However!    Interestingly a new observation.

Originally the node would show up as `online` or `offline`.  (etc)
With this new config, it doesn't.

Rather it shows up as the node like this:

![Screenshot from 2019-12-18 13-54-12](https://user-images.githubusercontent.com/39888280/71051945-f7d90b00-219d-11ea-8555-4b548a2e250e.png)

**Comment by Just-another-pleb** [comment] 2019-12-18 03:39
(You aren't going to like me)

After posting that and messing around making a bigger flow, it has stopped working.

Any ideas?

**Comment by Just-another-pleb** [comment] 2019-12-18 04:14
(again:  sorry.)

Update:
RasPi - 2a.   Stretch.
NR 0.20.5
This is what the flow looks like.

![Screenshot from 2019-12-18 15-10-43](https://user-images.githubusercontent.com/39888280/71055179-cf0a4300-21a8-11ea-8e6c-ae3c8d41557f.png)

NUC - Ubuntu 18.0.4 LTS
NR 1.0.3
This is the flow I originally made.
Looks nice.
It takes no time to 'deploy' a flow for testing reasons.

The RPI takes about 40 seconds.

So this is the flow on the NUC

![Screenshot from 2019-12-18 15-10-37](https://user-images.githubusercontent.com/39888280/71055268-11cc1b00-21a9-11ea-8a57-b48b6bd88f92.png)

Something is going on.

**Comment by DaveMDS** [comment] 2019-12-19 19:13
> HURRAY!
> 
> This config works!
> 
> ```
> [{"id":"47a3b1ab.b25ff8","type":"Tasmota Switch","z":"9245b569.9f881","broker":"8a2e80be.f7c928","device":"BAUHN-1","name":"Bauhn 1","topicMode":"0","cmndPrefix":"","statPrefix":"","telePrefix":"","outputs":3,"onValue":"","offValue":"","toggleValue":"","x":520,"y":1560,"wires":[["eec8a5ad.4a5dd"],["20c62106.1e6fde"],["33f8c8b1.e93cd8"]],"info":"Old device name\nBAUHN-1\n"},{"id":"8a2e80be.f7c928","type":"mqtt-broker","z":"","name":"MQTT host","broker":"192.168.0.99","port":"1883","clientid":"","usetls":false,"compatmode":true,"keepalive":"60","cleansession":true,"birthTopic":"ARDUINO_STATUS","birthQos":"2","birthPayload":"connected","willTopic":"ARDUINO_STATUS","willQos":"0","willPayload":"disconnected"}]
> ```
> 
> Maybe what was stumping me was in the advanced settings.
> 
> I had the `stat` line with text in it which was _wrong_/not helping.
> 
> However! Interestingly a new observation.
> 
> Originally the node would show up as `online` or `offline`. (etc)
> With this new config, it doesn't.
> 
> Rather it shows up as the node like this:
> 
> ![Screenshot from 2019-12-18 13-54-12](https://user-images.githubusercontent.com/39888280/71051945-f7d90b00-219d-11ea-8555-4b548a2e250e.png)

Indeed this one is correct configuration, and the node is correctly working.
The label you see is the correct one, "online" show up until the node does not know the state
of the relays, once it knows (and should keep a fraction of a second) it show the state of the 
relays in the label, "Off - Off - Off" means all your relays are open, if you toggle the first relay you should then see "On - Off - Off".

**Comment by DaveMDS** [comment] 2019-12-19 19:37
> (again: sorry.)
> 
> Update:
> RasPi - 2a. Stretch.
> NR 0.20.5
> This is what the flow looks like.
> 
> ![Screenshot from 2019-12-18 15-10-43](https://user-images.githubusercontent.com/39888280/71055179-cf0a4300-21a8-11ea-8e6c-ae3c8d41557f.png)
> 
> NUC - Ubuntu 18.0.4 LTS
> NR 1.0.3
> This is the flow I originally made.
> Looks nice.
> It takes no time to 'deploy' a flow for testing reasons.
> 
> The RPI takes about 40 seconds.
> 
> So this is the flow on the NUC
> 
> ![Screenshot from 2019-12-18 15-10-37](https://user-images.githubusercontent.com/39888280/71055268-11cc1b00-21a9-11ea-8a57-b48b6bd88f92.png)
> 
> Something is going on.

yes, something strange :D
you should just see 3 "Off", not 8 as in your shoot...I have no idea what is causing that behavior, seems to me your device sent a message like `stat/BAUHN-1/POWER8`, infact the node looks at the last number in the message and assign to that channel ... :/

To help you further I really need to see all the mqtt traffic to/from your tasmota when you toggle a switch. It is quite easy to do, just add an mqtt-in node with topic "#" and connect to a debug node to see ALL the mqtt traffic in the debug pane.
If you are brave you can also show the traffic from a single device setting a topic like `+/BAUHN-1/#`

Maybe I will also need the mqtt traffic generated while you power on/off the device?

PS: "sonoff1" is the name of my device! in your case its BAUHN-1

**Comment by eiktyrner** [comment] 2020-01-04 18:15
I'm having similar issues. Not seeing any output at all from the node when it's connected like this.
![2](https://user-images.githubusercontent.com/4710252/71769847-41f41780-2f26-11ea-9f70-adf6d482bc61.PNG)

However if I add a "mqtt-in" node with topic # it starts working, even if it's not connected to anything.
![1](https://user-images.githubusercontent.com/4710252/71769846-41f41780-2f26-11ea-880c-4df502c4378a.PNG)

Does that make any sense to you @DaveMDS ?

**Comment by DaveMDS** [comment] 2020-01-05 11:16
@eiktyrner: No, it does not make any sense to me... but... I have the same issue with one of my sonoff :P

The only device that expose this issue (need a generic mqtt-node to work) for me is a Sonoff Wall 2CH, all other sonoff I have works without any issue... this can maybe an issue with multi channels devices, as it is the only 2ch device I own. Do you have a single channel device to test? just to confirm the issue is related to multi-channel devices.

Btw thanks very much for the report! Now I have a reproducible issue and maybe I can fix that...stay tuned :)

**Comment by florianwgnr** [comment] 2020-01-05 15:20
> However if I add a "mqtt-in" node with topic # it starts working, even if it's not connected to anything.

Got exactly the same issue and adding the "#" also solved the problem for me.

**Comment by eiktyrner** [comment] 2020-01-06 09:57
@DaveMDS I have a single channel device of the same brand on order, let me get back to you in a couple of days with results. Thanks for having a look at this issue!

**Comment by DaveMDS** [comment] 2020-01-06 20:10
> > However if I add a "mqtt-in" node with topic # it starts working, even if it's not connected to anything.
> 
> Got exactly the same issue and adding the "#" also solved the problem for me.
@florianwgnr: what device? how many channels?

**Comment by florianwgnr** [comment] 2020-01-06 20:20
> @florianwgnr: what device are you using? how many channels?

I am using a 2-Channel plug "Gosund SP112" with tasmota.

**Comment by DaveMDS** [comment] 2020-01-06 20:29
Ok, thanks. Now I'm sure the issue is related to multi channels devices

**Comment by eiktyrner** [comment] 2020-01-07 19:29
I tried with a 1-channel device (Deltaco SH-P01) and it's working fine without the extra node. So yeah it looks like it's multi channel devices

**Comment by DaveMDS** [comment] 2020-01-07 21:06
OK guys, I just published the 0.9.2 release that fix this issue.
Now my 2CH device works without issue, please update and confirm

**Comment by Just-another-pleb** [comment] 2020-01-09 03:33
Not good news from me with the update.

3 outlet board, more than 3 status messages.

Just letting you know.

![Screenshot from 2020-01-09 13-45-19](https://user-images.githubusercontent.com/39888280/72035762-e5f60e00-32ec-11ea-848c-db01deb10d0d.png)
![Screenshot from 2020-01-09 13-46-40](https://user-images.githubusercontent.com/39888280/72035763-e5f60e00-32ec-11ea-9fc9-a1f501c3d228.png)

**Comment by DaveMDS** [comment] 2020-01-09 07:40
@Just-another-pleb this is another issue, not the one I have fixed. 
Does the node works (apart from the status label I mean) ? 
turning on/off works? 
messages in the 3 node outputs works?
please provide the json of this last flow

**Comment by Just-another-pleb** [comment] 2020-01-09 08:27
Sorry Dave.   My mistake.

It worked when I tested it - I just got other Tasmota stuff and was testing them as well.
I went through the on/off of all 3 and they worked to the best of my knowledge.

I don't get what you mean by the last line:
> please provide the json on this last flow

**Comment by DaveMDS** [comment] 2020-01-09 20:52
Hmm, I have no idea whats going on in your setup that cause the status label to show so many times.
Please try this simple flow:

![simple1](https://user-images.githubusercontent.com/52688/72101861-f8d90480-3325-11ea-8f87-a91d7a911f87.png)

```
[{"id":"5606a996.b14688","type":"tab","label":"Flow 1","disabled":false,"info":""},{"id":"e9735c76.bb91c8","type":"Tasmota Switch","z":"5606a996.b14688","broker":"7d944f80.e9826","device":"sonoff-w01","name":"","fullTopic":"","cmndPrefix":"","statPrefix":"","telePrefix":"","outputs":3,"onValue":"","offValue":"","toggleValue":"","x":350,"y":120,"wires":[[],[],[]]},{"id":"fa426b90.f9afe8","type":"inject","z":"5606a996.b14688","name":"","topic":"switch1","payload":"toggle","payloadType":"str","repeat":"","crontab":"","once":false,"onceDelay":0.1,"x":170,"y":80,"wires":[["e9735c76.bb91c8"]]},{"id":"fc3f02d0.20ddc8","type":"inject","z":"5606a996.b14688","name":"","topic":"switch2","payload":"toggle","payloadType":"str","repeat":"","crontab":"","once":false,"onceDelay":0.1,"x":170,"y":120,"wires":[["e9735c76.bb91c8"]]},{"id":"6f508ec.5403c7","type":"inject","z":"5606a996.b14688","name":"","topic":"switch3","payload":"toggle","payloadType":"str","repeat":"","crontab":"","once":false,"onceDelay":0.1,"x":170,"y":160,"wires":[["e9735c76.bb91c8"]]},{"id":"39228fbc.d0af08","type":"mqtt in","z":"5606a996.b14688","name":"","topic":"stat/sonoff-w01/#","qos":"2","datatype":"auto","broker":"7d944f80.e9826","x":160,"y":240,"wires":[["ca843dc4.0ba8e8"]]},{"id":"ca843dc4.0ba8e8","type":"debug","z":"5606a996.b14688","name":"","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"false","x":350,"y":240,"wires":[]},{"id":"7d944f80.e9826","type":"mqtt-broker","z":"","name":"MQTT Broker 170","broker":"192.168.1.170","port":"1883","clientid":"node-red-arch","usetls":false,"compatmode":false,"keepalive":"60","cleansession":true,"birthTopic":"","birthQos":"0","birthPayload":"","closeTopic":"","closeQos":"0","closePayload":"","willTopic":"","willQos":"0","willPayload":""}]
```
Import this in a new flow and change config to match your setup:
1. Change `sonoff-w01` with the name of your device (`BAUHN-1` I think) in both the Tasmota and the mqtt nodes
2. Select your MQTT broker in both the Tasmota and the mqtt nodes
3. DON'T CHANGE ANYTHING ELSE  :-)

Now clear the debug panel (`crtl-alt-l`) and click `Deploy->Restart Flows `, you should see something like this:
![simple2](https://user-images.githubusercontent.com/52688/72103168-ef9d6700-3328-11ea-977d-031cff445ce4.png)
I really need to see the output of your debug panel to understand the problem
NOTE: If you get too much noise in the debug panel try to disable all the other flows for the test

**Comment by DaveMDS** [comment] 2020-04-08 19:51
No reply from the user since a long time, closing.
please reopen if your are still affected

**Closed by DaveMDS** 2020-04-08 19:51 UTC
