### ISSUE TITLE
Switch node sends a topic when multiple outputs are enabled

### ISSUE THREAD

**Issue by sbrown4** [DaveMDS/node-red-contrib-tasmota#42] opened 2022-10-26 14:25 UTC
If multiple switch node outputs are enabled, a topic containing a switch id is still included in the message. This appears to be incompatible with the light node which expects no topic for mode 1 (simple) and a predefined set of topics for the other modes. I get an Invalid message error. I had to insert a function to remove the topic from the message to use mode 1.

Steve

**Comment by DaveMDS** [comment] 2022-11-02 19:33
Hi, indeed this seems a wrong behavior
but I don't know how to solve this issue without changing the node configuration (and thus breaking all users)

The problem is that in config "1 channel" and "all merged" are the same option, so in this case I don't know if I should emit the topic or not...  :/

any ideas? did you looked at the code that send the message? (src/nodes/switch.js, lines 93/102)

**Comment by sbrown4** [comment] 2022-11-03 11:38
I made this change. Maybe, not the best, but it works.
I made the change in my .node-red directory and had only to restart node-red.
Thanks for your work. It really simplified setting up my switches.
```
--- ../switch.js.orig	2022-11-03 06:33:42.695055734 -0400
+++ ../switch.js.working	2022-11-03 06:31:58.130735309 -0400
@@ -95,9 +95,9 @@
         // everything to the same (single) output
         this.send(msg)
       } else {
-        // or send to the correct output
+        // or send to the correct output with no topic
         const msgList = Array(this.config.outputs).fill(null)
-        msgList[channel - 1] = msg
+        msgList[channel - 1] = { payload: (status === 'On') }
         this.send(msgList)
       }
     }

```

**Comment by DaveMDS** [comment] 2022-11-03 19:08
Indeed this is what I also tried, then realized the 1 channel issue...
need to find another way to solve this without breaking (too much) old usages

**Closed** 2023-11-04 09:11 UTC
Labels: bug
